export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdbcf",
        "on-secondary-fixed-variant": "#5e289b",
        "on-tertiary-fixed-variant": "#474646",
        "tertiary-fixed": "#e5e2e1",
        "inverse-on-surface": "#303030",
        "error-container": "#93000a",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#e3bfb3",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#832700",
        "outline": "#aa897f",
        "surface-variant": "#353535",
        "surface-container-highest": "#353535",
        "secondary-container": "#602b9d",
        "on-error": "#690005",
        "on-tertiary": "#313030",
        "surface-tint": "#ffb59c",
        "primary": "#ffb59c",
        "on-background": "#e2e2e2",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-primary": "#5c1900",
        "on-primary-container": "#561700",
        "secondary-fixed": "#eedbff",
        "surface": "#131313",
        "on-secondary": "#460283",
        "tertiary": "#c8c6c5",
        "inverse-primary": "#ab3600",
        "primary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#1c1b1b",
        "secondary-fixed-dim": "#dab9ff",
        "primary-container": "#ff5f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1b1b",
        "surface-dim": "#131313",
        "background": "#131313",
        "surface-container": "#1f1f1f",
        "on-tertiary-container": "#2d2c2c",
        "inverse-surface": "#e2e2e2",
        "outline-variant": "#5b4138",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#cfa7ff",
        "on-primary-fixed": "#390c00",
        "tertiary-container": "#959393",
        "secondary": "#dab9ff",
        "surface-bright": "#393939",
        "on-secondary-fixed": "#2a0053",
      },

      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },

      spacing: {
        "container-padding": "24px",
        "stack-md": "16px",
        "unit": "8px",
        "stack-lg": "32px",
        "gutter": "16px",
        "section-gap": "48px",
        "stack-sm": "8px",
      },

      fontFamily: {
        "headline-lg": ["Epilogue", "sans-serif"],
        "headline-xl": ["Epilogue", "sans-serif"],
        "headline-md": ["Epilogue", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },

      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};